name: frontend
version: 0.0.0.1
github: "ibizaman/hs-template-nix-reflexfrp/frontend"
license: BSD3
author: "Pierre Penninckx"
maintainer: "ibizapeanut@gmail.com"
copyright: "2020 Pierre Penninckx"

description: Please see the README on GitHub at <https://ibizaman/hs-template-nix-reflexfrp/frontend>

dependencies:
    # base must match what comes with ghc
    - base == 4.12.0.0
    - common
    - containers == 0.6.0.1
    - text >= 1.2.3.0 && < 1.2.4
    - reflex == 0.8.1.0
    - reflex-dom == 0.6.1.0
    - servant == 0.16.2
    - servant-server == 0.16.2
    - servant-reflex == 0.3.6

default-extensions:
    - OverloadedStrings

library:
    source-dirs: src
    dependencies: {}

executables:
    frontend-exe:
        main: main.hs
        source-dirs: app
        dependencies:
            - frontend
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-record-updates
    - -fwarn-incomplete-uni-patterns
    - -fwarn-missing-signatures
    - -fwarn-name-shadowing
    - -fwarn-overlapping-patterns
    - -fwarn-tabs
    - -fwarn-unused-imports
