name: backend
version: 0.0.0.1
github: "ibizaman/hs-template-nix-reflexfrp/backend"
license: BSD3
author: "Pierre Penninckx"
maintainer: "ibizapeanut@gmail.com"
copyright: "2020 Pierre Penninckx"

description: Please see the README on GitHub at <https://ibizaman/hs-template-nix-reflexfrp/backend>

dependencies:
    # base must match what comes with ghc
    - base == 4.12.0.0

default-extensions:
    - OverloadedStrings

library:
    source-dirs: src
    dependencies: {}

executables:
    backend-exe:
        main: main.hs
        source-dirs: app
        dependencies:
            - backend
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

tests:
    backend-test:
        main: Spec.hs
        source-dirs: test
        dependencies:
            - backend
            - hspec == 2.7.1
            - hspec-core == 2.7.1
            - hspec-discover == 2.7.1
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-record-updates
    - -fwarn-incomplete-uni-patterns
    - -fwarn-missing-signatures
    - -fwarn-name-shadowing
    - -fwarn-overlapping-patterns
    - -fwarn-tabs
    - -fwarn-unused-imports
