name: "build, test and package"
on:
    pull_request:
    push:
jobs:
    shell:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: ibizaman
                  authToken: "${{ secrets.CACHIX_IBIZAMAN_AUTHTOKEN }}"

            - run: nix-build shell.nix
            - run: make cabals
            - run: nix-shell --pure --run haskell-language-server-wrapper
            - run: nix-build shell.ghcjs.nix

    build-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: ibizaman
                  authToken: "${{ secrets.CACHIX_IBIZAMAN_AUTHTOKEN }}"

            - run: make backend-release-build
            - uses: actions/upload-artifact@v2
              with:
                  name: backend-exe
                  path: backend-result/bin/backend-exe

            - run: make frontend-desktop-release-build
            - uses: actions/upload-artifact@v2
              with:
                  name: frontend-desktop-exe
                  path: frontend-desktop-result/bin/frontend-exe

            - run: make frontend-warp-release-build
            - uses: actions/upload-artifact@v2
              with:
                  name: frontend-warp-exe
                  path: frontend-warp-result/bin/frontend-exe

            - run: make frontend-release-build
            - uses: actions/upload-artifact@v2
              with:
                  name: frontend-exe
                  path: frontend-result/bin/frontend-exe
